[package]
name = "day-night-cycle-to-redis"
version = "0.1.0"
authors = ["Bernd Vogt <bernd.vogt@sourcepit.org>"]

[dependencies]
clap = "=2.33.0"
common_failures = "=0.1.1"
failure = "=0.1.6"
log = "=0.4.8"
stderrlog = "=0.4.3"
chrono = {version="=0.4.10", features = ["std"]}
redis = "=0.15.1"
